"""initial schema

Revision ID: cf96632c5905
Revises: 
Create Date: 2026-08-16 19:27:42.713455
"""
from alembic import op
import sqlalchemy as sa


revision = 'cf96632c5905'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=False),
    sa.Column('fpid', sa.Integer(), nullable=True),
    sa.Column('mflid', sa.Integer(), nullable=True),
    sa.Column('player_dk_id', sa.Integer(), nullable=True),
    sa.Column('gsis_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_fpid'), 'players', ['fpid'], unique=False)
    op.create_index(op.f('ix_players_gsis_id'), 'players', ['gsis_id'], unique=False)
    op.create_index(op.f('ix_players_player_dk_id'), 'players', ['player_dk_id'], unique=False)
    op.create_table('slates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=64), nullable=True),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_group_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('lifetime', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustments_slate_id'), 'adjustments', ['slate_id'], unique=False)
    op.create_table('build_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('home', sa.String(length=8), nullable=False),
    sa.Column('away', sa.String(length=8), nullable=False),
    sa.Column('start_time', sa.String(length=64), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('home_spread', sa.Float(), nullable=True),
    sa.Column('home_implied', sa.Float(), nullable=True),
    sa.Column('away_implied', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slate_id', 'home', 'away')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_captured_at'), 'odds_snapshots', ['captured_at'], unique=False)
    op.create_table('pool_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('sims_blob_key', sa.String(length=256), nullable=True),
    sa.Column('n_sims', sa.Integer(), nullable=True),
    sa.Column('sims_seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_versions_slate_id'), 'pool_versions', ['slate_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_name', sa.String(length=128), nullable=False),
    sa.Column('raw_team', sa.String(length=8), nullable=False),
    sa.Column('raw_position', sa.String(length=8), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_player_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_key', sa.String(length=256), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'raw_key')
    )
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.Integer(), nullable=False),
    sa.Column('contest_key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=True),
    sa.Column('field_size', sa.Integer(), nullable=True),
    sa.Column('max_entries_per_user', sa.Integer(), nullable=True),
    sa.Column('total_payouts', sa.Float(), nullable=True),
    sa.Column('payout_curve', sa.JSON(), nullable=False),
    sa.Column('build_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['build_profile_id'], ['build_profiles.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slate_id', 'contest_key')
    )
    op.create_index(op.f('ix_contests_contest_key'), 'contests', ['contest_key'], unique=False)
    op.create_index(op.f('ix_contests_slate_id'), 'contests', ['slate_id'], unique=False)
    op.create_table('lineup_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.Integer(), nullable=False),
    sa.Column('pool_version_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('sims_blob_key', sa.String(length=256), nullable=True),
    sa.Column('n_eff', sa.Float(), nullable=True),
    sa.Column('n_eff_flag', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_version_id'], ['pool_versions.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineup_sets_slate_id'), 'lineup_sets', ['slate_id'], unique=False)
    op.create_table('pool_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_version_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=False),
    sa.Column('opponent', sa.String(length=8), nullable=False),
    sa.Column('game_key', sa.String(length=32), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('dvp_rank', sa.Integer(), nullable=True),
    sa.Column('projection', sa.Float(), nullable=False),
    sa.Column('floor', sa.Float(), nullable=False),
    sa.Column('ceiling', sa.Float(), nullable=False),
    sa.Column('stddev', sa.Float(), nullable=False),
    sa.Column('ownership', sa.Float(), nullable=False),
    sa.Column('implied_opp_total', sa.Float(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('draftable_ids', sa.JSON(), nullable=False),
    sa.Column('sim_col', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['pool_version_id'], ['pool_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_players_pool_version_id'), 'pool_players', ['pool_version_id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_set_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('projection', sa.Float(), nullable=False),
    sa.Column('ceiling', sa.Float(), nullable=False),
    sa.Column('ownership', sa.Float(), nullable=False),
    sa.Column('lineup_type', sa.String(length=32), nullable=False),
    sa.Column('skeleton_key', sa.String(length=64), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('evaluation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lineup_set_id'], ['lineup_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineups_lineup_set_id'), 'lineups', ['lineup_set_id'], unique=False)
    op.create_table('ownership_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=128), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('drafted_pct', sa.Float(), nullable=True),
    sa.Column('fpts', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_observations_contest_id'), 'ownership_observations', ['contest_id'], unique=False)
    op.create_table('contest_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('dk_entry_id', sa.String(length=32), nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['lineup_id'], ['lineups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'dk_entry_id')
    )
    op.create_index(op.f('ix_contest_entries_contest_id'), 'contest_entries', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_entries_dk_entry_id'), 'contest_entries', ['dk_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contest_entries_dk_entry_id'), table_name='contest_entries')
    op.drop_index(op.f('ix_contest_entries_contest_id'), table_name='contest_entries')
    op.drop_table('contest_entries')
    op.drop_index(op.f('ix_ownership_observations_contest_id'), table_name='ownership_observations')
    op.drop_table('ownership_observations')
    op.drop_index(op.f('ix_lineups_lineup_set_id'), table_name='lineups')
    op.drop_table('lineups')
    op.drop_index(op.f('ix_pool_players_pool_version_id'), table_name='pool_players')
    op.drop_table('pool_players')
    op.drop_index(op.f('ix_lineup_sets_slate_id'), table_name='lineup_sets')
    op.drop_table('lineup_sets')
    op.drop_index(op.f('ix_contests_slate_id'), table_name='contests')
    op.drop_index(op.f('ix_contests_contest_key'), table_name='contests')
    op.drop_table('contests')
    op.drop_table('source_maps')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_pool_versions_slate_id'), table_name='pool_versions')
    op.drop_table('pool_versions')
    op.drop_index(op.f('ix_odds_snapshots_captured_at'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_table('jobs')
    op.drop_table('games')
    op.drop_table('build_profiles')
    op.drop_index(op.f('ix_adjustments_slate_id'), table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_table('users')
    op.drop_table('slates')
    op.drop_index(op.f('ix_players_player_dk_id'), table_name='players')
    op.drop_index(op.f('ix_players_gsis_id'), table_name='players')
    op.drop_index(op.f('ix_players_fpid'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
